# Generated by Django 5.0.2 on 2024-02-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=4)),
                ('number', models.IntegerField(default=0)),
                ('reported_fname', models.CharField(max_length=20)),
                ('reported_lName', models.CharField(max_length=20)),
                ('reported_comp_id', models.CharField(max_length=7)),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
