# Generated by Django 5.0.2 on 2024-03-05 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0004_rename_reported_lname_report_reported_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
