# Generated by Django 5.0.2 on 2024-03-05 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0005_report_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
