# Generated by Django 5.0.2 on 2024-03-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0003_userprofile_role_userprofile_site_admin'),
        ('team_b_06', '0006_alter_report_number'),
    ]

    operations = [
    ]
