# Generated by Django 5.0.2 on 2024-03-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0007_merge_20240316_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='No Title (Default)', max_length=100),
        ),
    ]
