# Generated by Django 5.0.2 on 2024-03-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0007_merge_20240316_1636'),
        ('team_b_06', '0008_report_title'),
    ]

    operations = [
    ]
