# Generated by Django 5.0.2 on 2024-03-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0009_merge_0007_merge_20240316_1636_0008_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
