# Generated by Django 5.0.2 on 2024-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0011_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='staff_approved',
            field=models.BooleanField(default=False),
        ),
    ]
