# Generated by Django 5.0.2 on 2024-03-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0012_report_admin_approved_report_staff_approved'),
        ('team_b_06', '0014_report_status'),
    ]

    operations = [
    ]
