# Generated by Django 5.0.2 on 2024-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0015_merge_20240329_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
