# Generated by Django 5.0.2 on 2024-03-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0015_merge_20240329_1641'),
        ('team_b_06', '0016_report_note'),
    ]

    operations = [
    ]
