# Generated by Django 5.0.2 on 2024-04-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0017_merge_0015_merge_20240329_1641_0016_report_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='staff_approved',
            new_name='instructor_approved',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='visibility',
            new_name='whisteblower_approved',
        ),
    ]
