# Generated by Django 5.0.3 on 2024-04-08 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0017_merge_0015_merge_20240329_1641_0016_report_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Student', max_length=30),
        ),
    ]
