# Generated by Django 5.0.2 on 2024-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0018_report_submit_date_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('GR', 'Grading'), ('O', 'Other'), ('AI', 'Accessibility and Inclusivity'), ('GF', 'General Feedback'), ('SM', 'Subject Material'), ('CC', 'Classroom Conduct/Behavior')], default='GF', max_length=5000),
        ),
    ]
