# Generated by Django 5.0.2 on 2024-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0019_report_awaiting_instructor_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comp_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
