# Generated by Django 5.0.2 on 2024-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0018_report_submit_date_alter_userprofile_role'),
        ('team_b_06', '0020_alter_userprofile_comp_id'),
    ]

    operations = [
    ]
