# Generated by Django 5.0.2 on 2024-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0020_alter_report_tag'),
        ('team_b_06', '0021_merge_20240412_1235'),
    ]

    operations = [
    ]
