# Generated by Django 5.0.2 on 2024-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0023_alter_report_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('AI', 'Accessibility and Inclusivity'), ('GR', 'Grading'), ('N', 'None'), ('SM', 'Subject Material'), ('CC', 'Classroom Conduct/Behavior'), ('GF', 'General Feedback'), ('O', 'Other')], default='N', max_length=5000),
        ),
    ]
