# Generated by Django 5.0.2 on 2024-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0026_alter_report_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('CC', 'Classroom Conduct/Behavior'), ('GF', 'General Feedback'), (None, 'None'), ('GR', 'Grading'), ('AI', 'Accessibility and Inclusivity'), ('O', 'Other'), ('SM', 'Subject Material')], default=None, max_length=5000),
        ),
    ]
