# Generated by Django 5.0.2 on 2024-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0030_alter_report_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('GR', 'Grading'), ('AI', 'Accessibility and Inclusivity'), ('O', 'Other'), (None, 'None'), ('SM', 'Subject Material'), ('GF', 'General Feedback'), ('CC', 'Classroom Conduct/Behavior')], default=None, max_length=5000),
        ),
    ]
