# Generated by Django 5.0.2 on 2024-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0033_alter_report_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('SM', 'Subject Material'), ('GR', 'Grading'), ('O', 'Other'), ('AI', 'Accessibility and Inclusivity'), ('CC', 'Classroom Conduct/Behavior'), ('GF', 'General Feedback'), (None, 'None')], default=None, max_length=5000),
        ),
    ]
