# Generated by Django 5.0.2 on 2024-04-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0022_merge_0020_alter_report_tag_0021_merge_20240412_1235'),
        ('team_b_06', '0035_alter_report_tag'),
    ]

    operations = [
    ]
