# Generated by Django 5.0.2 on 2024-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0036_merge_20240413_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('N', 'None'), ('CC', 'Classroom Conduct/Behavior'), ('GR', 'Grading'), ('SM', 'Subject Material'), ('AI', 'Accessibility and Inclusivity'), ('GF', 'General Feedback'), ('O', 'Other')], default='N', max_length=5000),
        ),
    ]
