# Generated by Django 5.0.2 on 2024-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0037_alter_report_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter_comp_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
