# Generated by Django 5.0.2 on 2024-04-28 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_b_06', '0038_report_reporter_comp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='mnemonic',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_comp_id',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comp_id',
            field=models.CharField(default='', max_length=7),
        ),
    ]
